"""Send random arm positions to the deploy controller via LCM.

Mimics the nudge_arms_position event from training: smoothly moves arm PD
targets at constant speed toward random goals, resamples when reached.

Channel: "arm_action"  (arm_action_lcmt, 14 doubles)
Joint order: [left 7] + [right 7], each: shoulder_pitch, shoulder_roll,
  shoulder_yaw, elbow, wrist_roll, wrist_pitch, wrist_yaw.

Usage:
    python scripts/send_random_arms.py [--speed 0.5] [--offset 0.5] [--hz 50]
"""
from __future__ import annotations

import argparse
import random
import struct
import time

import lcm

# ── LCM message encoding ────────────────────────────────────────────────
# Matches arm_action_lcmt generated by lcm-gen 1.5.0 (hash 0x692f2be95563f8fe).
_BASE_HASH = 0x692F2BE95563F8FE
_FINGERPRINT = ((_BASE_HASH << 1) + (_BASE_HASH >> 63)) & 0xFFFFFFFFFFFFFFFF
_PACKED_FINGERPRINT = struct.pack(">Q", _FINGERPRINT)


def encode_arm_action(positions: list[float]) -> bytes:
    """Encode 14 doubles as arm_action_lcmt wire format."""
    assert len(positions) == 14
    return _PACKED_FINGERPRINT + struct.pack(">14d", *positions)


# ── Joint limits from g1.xml ────────────────────────────────────────────
# (shoulder_pitch, shoulder_roll, shoulder_yaw, elbow,
#  wrist_roll, wrist_pitch, wrist_yaw)
JOINT_LIMITS_LEFT = [
    (-3.0892, 2.6704),   # shoulder_pitch
    (-1.5882, 2.2515),   # shoulder_roll
    (-2.618, 2.618),     # shoulder_yaw
    (-1.0472, 2.0944),   # elbow
    (-1.9722, 1.9722),   # wrist_roll
    (-1.6144, 1.6144),   # wrist_pitch
    (-1.6144, 1.6144),   # wrist_yaw
]
JOINT_LIMITS_RIGHT = [
    (-3.0892, 2.6704),   # shoulder_pitch
    (-2.2515, 1.5882),   # shoulder_roll  (mirrored)
    (-2.618, 2.618),     # shoulder_yaw
    (-1.0472, 2.0944),   # elbow
    (-1.9722, 1.9722),   # wrist_roll
    (-1.6144, 1.6144),   # wrist_pitch
    (-1.6144, 1.6144),   # wrist_yaw
]
JOINT_LIMITS = JOINT_LIMITS_LEFT + JOINT_LIMITS_RIGHT  # 14 joints

# Default arm positions from deploy.yaml
DEFAULT_POS = [
    -1.6, 0.0, 0.0, 1.57, 0.0, 0.0, 0.0,  # left
    -1.6, 0.0, 0.0, 1.57, 0.0, 0.0, 0.0,  # right
]


def clamp(val: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, val))


def sample_goal(current: list[float], offset_range: float) -> list[float]:
    """Sample a new random goal within offset_range of current, clamped to limits."""
    goal = []
    for i in range(14):
        lo, hi = JOINT_LIMITS[i]
        raw = current[i] + random.uniform(-offset_range, offset_range)
        goal.append(clamp(raw, lo, hi))
    return goal


def main() -> None:
    parser = argparse.ArgumentParser(description="Send random arm positions via LCM")
    parser.add_argument("--speed", type=float, default=0.5,
                        help="Movement speed in rad/s (default: 0.5)")
    parser.add_argument("--offset", type=float, default=0.5,
                        help="Random offset range in rad (default: 0.5)")
    parser.add_argument("--hz", type=float, default=50.0,
                        help="Publish rate in Hz (default: 50)")
    args = parser.parse_args()

    lc = lcm.LCM()
    dt = 1.0 / args.hz

    positions = list(DEFAULT_POS)
    goal = sample_goal(positions, args.offset)

    print(f"Sending random arm positions on 'arm_action' @ {args.hz} Hz")
    print(f"  speed={args.speed} rad/s, offset_range={args.offset} rad")
    print(f"  default pos (L): {DEFAULT_POS[:7]}")
    print(f"  default pos (R): {DEFAULT_POS[7:]}")
    print("Press Ctrl+C to stop.\n")

    step = 0
    try:
        while True:
            # Move toward goal at constant speed.
            max_step = args.speed * dt
            reached = True
            for i in range(14):
                diff = goal[i] - positions[i]
                if abs(diff) > 0.01:
                    reached = False
                move = clamp(diff, -max_step, max_step)
                positions[i] += move

            # Resample goal when reached.
            if reached:
                goal = sample_goal(positions, args.offset)

            # Publish.
            data = encode_arm_action(positions)
            lc.publish("arm_action", data)

            step += 1
            if step % int(args.hz * 2) == 0:  # print every 2 seconds
                print(
                    f"[step={step}] "
                    f"L: [{', '.join(f'{p:.2f}' for p in positions[:7])}]  "
                    f"R: [{', '.join(f'{p:.2f}' for p in positions[7:])}]"
                )

            time.sleep(dt)
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
